### PR TITLE
Change Index Value from Text to Key

### LINKED ISSUE #29: Change `Index Value` from `Text` to `Key`
Per https://github.com/lens/lens-aeson/pull/46.

### PR DESCRIPTION
**Pull request by sjshuck**
Closes #29.

### CODE REVIEW

**Comment by fosskers** [comment]
Should I still hold off on making a release?

**Comment by sjshuck** [comment]
> Should I still hold off on making a release?

I would hold off until upstream releases a new version.  They don't (really) have any open issues currently, so I expect @RyanGlScott or @ekmett will do that in the not too distant future.

**Comment by RyanGlScott** [comment]
If it would be helpful, I can cut a new Hackage release of `lens-aeson` this weekend.

**Comment by fosskers** [comment]
That would be great, thanks!

**Comment by ekmett** [comment]
no objection here

**Comment by RyanGlScott** [comment]
I've published [`lens-aeson-1.2`](https://hackage.haskell.org/package/lens-aeson-1.2) to Hackage.

**Comment by fosskers** [comment]
Thanks @RyanGlScott I'll push a release for this too.

**Comment by sjshuck** [comment]
Thanks everybody!

**Comment by fosskers** [comment]
Released! Thanks @sjshuck for your contributions on both sides.

**Pull request merged**
